
spark-submit co2Reader.py


drop table CO2_HDFS_H_EXT;

CREATE EXTERNAL TABLE  CO2_HDFS_H_EXT  (CARID float, MARQUE STRING,  MALUSBONUS FLOAT, REJET float, COUTENERGIE float)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE LOCATION 'output/TransformationCO2';